name: Build all examples
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          sparse-checkout: |
            .github
            junit-jupiter-starter-gradle
      - name: 'Set up JDK 24'
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          java-version: 24
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4          
      - name: Build with Gradle
        run: ./gradlew test
      
